Update README for ASF license and Travis badges.
apache/incubator-openwhisk-playground pull request #5
Opened 2017-07-07 21:37 UTC by mrutkows

2017-07-11 13:53 UTC, jberstler requested changes

2017-07-11 13:53 UTC, bjustin-ibm commented on README.md
> +[![Build Status](https://travis-ci.org/apache/incubator-openwhisk-playground.svg?branch=master)](https://travis-ci.org/apache/incubator-openwhisk-playground)
@mrutkows It appears that travis is not yet set up for this repo. The resulting badge just says "unknown" and clicking it takes me to a Travis page that says the repo is not active.

2017-07-12 19:32 UTC, mrutkows commented
@bjustin-ibm same approach as other repos. where it is not yet enabled; that is, comment it out in a GitHub markdown accepted way for now.

2017-07-12 19:34 UTC, jberstler approved these changes

2017-07-12 19:34 UTC, merged